-- ============================================================================
-- Treasure — Phase 1 (2D Web App) — Initial Schema + RLS
-- Generated 2026-07-07, based on treasure-project-spec.md v1.4
-- ============================================================================
--
-- ASSUMPTIONS BAKED INTO THIS MIGRATION (confirm before running in prod):
--
-- 1. AUTH STRATEGY (not yet explicitly confirmed with product owner):
--    Supabase Auth (auth.users) is used for ALL roles, including username-only
--    ones. Since auth.users requires an email, non-master-admin accounts get a
--    synthetic email of the form  "<username>@users.treasure.internal"
--    generated by the create-account Edge Function. The UI only ever asks for
--    a username; the Edge Function looks up/derives the synthetic email server
--    side. Master Admin uses a real email with Supabase's normal email
--    verification flow. Passwords are managed entirely by Supabase Auth
--    (bcrypt under the hood) — there is no password column in public.accounts.
--
-- 2. Resolved open questions from spec §10 (2026-07-07):
--    - Sessions are archived & browsable (append-only sessions table).
--    - bet_entries are immutable once inserted — no UPDATE/DELETE policy for
--      ANY role, including admin.
--    - No cap on users/partners per admin.
--    - Equal-split rounding remainder stays with Admin (already in spec §4.4;
--      enforced in the distribute-over-limit Edge Function, not in SQL).
--    - No partner-of-partner (sub-partner) hierarchy for Phase 1.
--
-- 3. All INSERT/UPDATE/DELETE on accounts, and all writes on the audit-style
--    tables (over_limit_records, share_history, partner_shares), happen via
--    Edge Functions using the service role key, which bypasses RLS entirely.
--    Intentionally NO client-facing INSERT policy exists for those tables —
--    absence of a policy = default deny under RLS.
--
-- 4. The live "Total Data" / "Over Limit" views (spec §5.2.5, computed from
--    bet_entries + an admin-adjustable set_limit) are NOT stored tables —
--    compute them with a query/view at read time. over_limit_records only
--    stores a frozen snapshot at the moment of a "Share to Partners" action,
--    tied to a share_history entry (see §7 below).
--
-- ============================================================================


-- ============================================================================
-- 0. EXTENSIONS
-- ============================================================================
create extension if not exists pgcrypto;


-- ============================================================================
-- 1. ENUM TYPES
-- ============================================================================
create type public.account_role as enum ('master_admin', 'admin', 'user', 'partner');
create type public.session_status as enum ('open', 'closed');
create type public.share_method_type as enum ('percentage', 'equally');
create type public.audience_role_type as enum ('user', 'partner');
create type public.audience_scope_type as enum ('all', 'selected');


-- ============================================================================
-- 2. CORE TABLES
-- ============================================================================

-- --------------------------------------------------------------------------
-- accounts — all Master Admin / Admin / User / Partner records
-- --------------------------------------------------------------------------
create table public.accounts (
  id                     uuid primary key default gen_random_uuid(),
  auth_user_id           uuid unique references auth.users (id) on delete cascade,
  role                   public.account_role not null,
  username               text not null,
  email                  text,                          -- populated only for master_admin
  email_verified_at      timestamptz,                    -- populated only for master_admin
  commission_rate        numeric(5,2) not null default 0 check (commission_rate >= 0 and commission_rate <= 100),
  payout_rate            integer not null default 0 check (payout_rate >= 0),
  data_share_percentage  numeric(5,2) check (data_share_percentage is null or (data_share_percentage >= 0 and data_share_percentage <= 100)),
  created_by             uuid references public.accounts (id),
  is_active              boolean not null default true,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),

  -- only partners carry a data_share_percentage
  constraint accounts_share_pct_only_for_partner
    check (role = 'partner' or data_share_percentage is null),

  -- master_admin must have an email; everyone else must not need one to log in
  constraint accounts_master_admin_email
    check (role <> 'master_admin' or email is not null)
);

create unique index accounts_username_unique_idx on public.accounts (lower(username));
create index accounts_created_by_idx on public.accounts (created_by);
create index accounts_role_idx on public.accounts (role);

-- --------------------------------------------------------------------------
-- sessions — one active session system-wide
-- --------------------------------------------------------------------------
create table public.sessions (
  id                  uuid primary key default gen_random_uuid(),
  label               text not null,                    -- e.g. "07-07-2026 (AM)"
  status              public.session_status not null default 'open',
  opened_at           timestamptz not null default now(),
  closed_at           timestamptz,
  winning_number      text check (winning_number is null or winning_number ~ '^[0-9]{2}$'),
  share_method        public.share_method_type,
  total_data_set_limit integer,                          -- admin's adjustable threshold, persisted for convenience
  created_by          uuid not null references public.accounts (id),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- enforce: only one 'open' session at a time, system-wide
create unique index sessions_single_open_idx on public.sessions ((true)) where (status = 'open');

create index sessions_status_idx on public.sessions (status);

-- --------------------------------------------------------------------------
-- entry_limits — per user, per session, per number (00-99)
-- --------------------------------------------------------------------------
create table public.entry_limits (
  id           uuid primary key default gen_random_uuid(),
  session_id   uuid not null references public.sessions (id) on delete cascade,
  user_id      uuid not null references public.accounts (id),
  number       text not null check (number ~ '^[0-9]{2}$'),
  limit_value  integer not null default 0 check (limit_value >= 0),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  unique (session_id, user_id, number)
);

create index entry_limits_session_user_idx on public.entry_limits (session_id, user_id);

-- --------------------------------------------------------------------------
-- limit_table_profiles / limit_table_profile_rows — saved, reusable templates
-- (needed for spec §5.2.4 "multiple limit table profiles can be saved and
-- re-applied"; not an explicit §7.1 table but required by that feature)
-- --------------------------------------------------------------------------
create table public.limit_table_profiles (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  created_by  uuid not null references public.accounts (id),
  created_at  timestamptz not null default now()
);

create table public.limit_table_profile_rows (
  id           uuid primary key default gen_random_uuid(),
  profile_id   uuid not null references public.limit_table_profiles (id) on delete cascade,
  number       text not null check (number ~ '^[0-9]{2}$'),
  limit_value  integer not null default 0 check (limit_value >= 0),

  unique (profile_id, number)
);

-- --------------------------------------------------------------------------
-- bet_entries — IMMUTABLE once inserted (resolved open question #2)
-- --------------------------------------------------------------------------
create table public.bet_entries (
  id          uuid primary key default gen_random_uuid(),
  session_id  uuid not null references public.sessions (id),
  user_id     uuid not null references public.accounts (id),
  number      text not null check (number ~ '^[0-9]{2}$'),
  amount      integer not null check (amount > 0),
  created_at  timestamptz not null default now()
);

create index bet_entries_session_user_number_idx on public.bet_entries (session_id, user_id, number);
create index bet_entries_session_idx on public.bet_entries (session_id);

-- --------------------------------------------------------------------------
-- share_history — header record for one "Share to Partners" action (immutable)
-- --------------------------------------------------------------------------
create table public.share_history (
  id                  uuid primary key default gen_random_uuid(),
  session_id          uuid not null references public.sessions (id),
  share_method        public.share_method_type not null,
  set_limit_used      integer not null,
  total_shared_amount integer not null default 0,
  created_by          uuid not null references public.accounts (id),
  created_at          timestamptz not null default now()
);

create index share_history_session_idx on public.share_history (session_id);

-- --------------------------------------------------------------------------
-- over_limit_records — frozen per-number snapshot for a share_history action
-- --------------------------------------------------------------------------
create table public.over_limit_records (
  id                uuid primary key default gen_random_uuid(),
  share_history_id  uuid not null references public.share_history (id) on delete cascade,
  session_id        uuid not null references public.sessions (id),
  number            text not null check (number ~ '^[0-9]{2}$'),
  total_amount      integer not null,
  limit_value       integer not null,
  over_limit_amount integer not null check (over_limit_amount >= 0),
  created_at        timestamptz not null default now()
);

create index over_limit_records_share_history_idx on public.over_limit_records (share_history_id);
create index over_limit_records_session_idx on public.over_limit_records (session_id);

-- --------------------------------------------------------------------------
-- partner_shares — per-partner, per-number allocation for a share_history action
-- --------------------------------------------------------------------------
create table public.partner_shares (
  id                uuid primary key default gen_random_uuid(),
  share_history_id  uuid not null references public.share_history (id) on delete cascade,
  session_id        uuid not null references public.sessions (id),
  partner_id        uuid not null references public.accounts (id),
  number            text not null check (number ~ '^[0-9]{2}$'),
  shared_amount     integer not null check (shared_amount >= 0),
  created_at        timestamptz not null default now()
);

create index partner_shares_session_partner_idx on public.partner_shares (session_id, partner_id);
create index partner_shares_share_history_idx on public.partner_shares (share_history_id);

-- --------------------------------------------------------------------------
-- warning_messages — admin -> user/partner banners
-- --------------------------------------------------------------------------
create table public.warning_messages (
  id             uuid primary key default gen_random_uuid(),
  session_id     uuid not null references public.sessions (id),
  message        text not null,
  audience_role  public.audience_role_type not null,
  audience_scope public.audience_scope_type not null default 'all',
  created_by     uuid not null references public.accounts (id),
  created_at     timestamptz not null default now()
);

create index warning_messages_session_idx on public.warning_messages (session_id);

-- --------------------------------------------------------------------------
-- session_targets — targeted recipients when a warning_message's
-- audience_scope = 'selected' (spec §7.1: "Links sessions to specific
-- users/partners for targeted ... messages")
-- --------------------------------------------------------------------------
create table public.session_targets (
  id                  uuid primary key default gen_random_uuid(),
  warning_message_id  uuid not null references public.warning_messages (id) on delete cascade,
  account_id          uuid not null references public.accounts (id),

  unique (warning_message_id, account_id)
);


-- ============================================================================
-- 3. updated_at TRIGGER HELPER
-- ============================================================================
create function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger accounts_set_updated_at
  before update on public.accounts
  for each row execute function public.set_updated_at();

create trigger sessions_set_updated_at
  before update on public.sessions
  for each row execute function public.set_updated_at();

create trigger entry_limits_set_updated_at
  before update on public.entry_limits
  for each row execute function public.set_updated_at();


-- ============================================================================
-- 4. RLS HELPER FUNCTIONS
-- (security definer so they can read public.accounts regardless of the
-- caller's own RLS visibility — standard Supabase pattern)
-- ============================================================================

create function public.current_account_id()
returns uuid
language sql stable security definer set search_path = public
as $$
  select id from public.accounts where auth_user_id = auth.uid();
$$;

create function public.current_role()
returns public.account_role
language sql stable security definer set search_path = public
as $$
  select role from public.accounts where auth_user_id = auth.uid();
$$;

create function public.is_master_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.accounts
    where auth_user_id = auth.uid() and role = 'master_admin'
  );
$$;

create function public.is_admin_or_above()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.accounts
    where auth_user_id = auth.uid() and role in ('admin', 'master_admin')
  );
$$;

-- true if target_account_id was created by the current admin, or the caller is master_admin
create function public.managed_by_current_admin(target_account_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select
    public.is_master_admin()
    or exists (
      select 1 from public.accounts a
      where a.id = target_account_id
        and a.created_by = public.current_account_id()
    );
$$;


-- ============================================================================
-- 5. ENABLE RLS
-- ============================================================================
alter table public.accounts                 enable row level security;
alter table public.sessions                 enable row level security;
alter table public.entry_limits             enable row level security;
alter table public.limit_table_profiles     enable row level security;
alter table public.limit_table_profile_rows enable row level security;
alter table public.bet_entries              enable row level security;
alter table public.share_history            enable row level security;
alter table public.over_limit_records       enable row level security;
alter table public.partner_shares           enable row level security;
alter table public.warning_messages         enable row level security;
alter table public.session_targets          enable row level security;


-- ============================================================================
-- 6. POLICIES
-- ============================================================================

-- ---------------------------------------------------------------- accounts
-- No INSERT policy: account creation happens only via the create-account
-- Edge Function (service role), which also provisions the matching
-- auth.users row (and synthetic email, if applicable). No DELETE policy:
-- deletion is a soft delete via UPDATE is_active = false.

create policy accounts_select on public.accounts
  for select to authenticated
  using (
    id = public.current_account_id()
    or public.is_master_admin()
    or created_by = public.current_account_id()
  );

create policy accounts_update_managed on public.accounts
  for update to authenticated
  using (
    public.is_master_admin()
    or created_by = public.current_account_id()
  )
  with check (
    public.is_master_admin()
    or created_by = public.current_account_id()
  );

-- ---------------------------------------------------------------- sessions
-- Everyone can see session status; only admin/master_admin can open/close,
-- set winning_number, share_method, or adjust total_data_set_limit.

create policy sessions_select_all on public.sessions
  for select to authenticated
  using (true);

create policy sessions_insert_admin on public.sessions
  for insert to authenticated
  with check (public.is_admin_or_above());

create policy sessions_update_admin on public.sessions
  for update to authenticated
  using (public.is_admin_or_above())
  with check (public.is_admin_or_above());

-- ------------------------------------------------------------ entry_limits
-- Users can read their own limits; admin/master_admin can read/write limits
-- for the users they manage. No policy allows a user to write their own.

create policy entry_limits_select on public.entry_limits
  for select to authenticated
  using (
    user_id = public.current_account_id()
    or public.managed_by_current_admin(user_id)
  );

create policy entry_limits_insert_admin on public.entry_limits
  for insert to authenticated
  with check (public.managed_by_current_admin(user_id));

create policy entry_limits_update_admin on public.entry_limits
  for update to authenticated
  using (public.managed_by_current_admin(user_id))
  with check (public.managed_by_current_admin(user_id));

create policy entry_limits_delete_admin on public.entry_limits
  for delete to authenticated
  using (public.managed_by_current_admin(user_id));

-- ----------------------------------------------- limit_table_profiles (+ rows)
create policy limit_table_profiles_all on public.limit_table_profiles
  for all to authenticated
  using (created_by = public.current_account_id() or public.is_master_admin())
  with check (created_by = public.current_account_id() or public.is_master_admin());

create policy limit_table_profile_rows_all on public.limit_table_profile_rows
  for all to authenticated
  using (
    exists (
      select 1 from public.limit_table_profiles p
      where p.id = profile_id
        and (p.created_by = public.current_account_id() or public.is_master_admin())
    )
  )
  with check (
    exists (
      select 1 from public.limit_table_profiles p
      where p.id = profile_id
        and (p.created_by = public.current_account_id() or public.is_master_admin())
    )
  );

-- ------------------------------------------------------------- bet_entries
-- SELECT: a user sees their own entries; admin/master_admin sees entries
-- from users they manage. Partners have NO access to raw bet_entries.
-- INSERT: only the user themselves, only while the session is open, and
-- only within their remaining limit for that number (defense-in-depth —
-- the validate-bet-entry Edge Function is the authoritative, race-safe check).
-- NO UPDATE/DELETE policy exists for anyone — entries are immutable.

create policy bet_entries_select on public.bet_entries
  for select to authenticated
  using (
    user_id = public.current_account_id()
    or public.managed_by_current_admin(user_id)
  );

create policy bet_entries_insert_own on public.bet_entries
  for insert to authenticated
  with check (
    user_id = public.current_account_id()
    and amount > 0
    and exists (
      select 1 from public.sessions s
      where s.id = bet_entries.session_id
        and s.status = 'open'
    )
    and (
      coalesce(
        (select el.limit_value from public.entry_limits el
         where el.session_id = bet_entries.session_id
           and el.user_id = bet_entries.user_id
           and el.number = bet_entries.number),
        0
      )
      >=
      amount + coalesce(
        (select sum(be.amount) from public.bet_entries be
         where be.session_id = bet_entries.session_id
           and be.user_id = bet_entries.user_id
           and be.number = bet_entries.number),
        0
      )
    )
  );

-- --------------------------------------------------------- share_history
-- Written only via the distribute-over-limit Edge Function (service role).
-- No client INSERT/UPDATE/DELETE policy. Readable by admin/master_admin.

create policy share_history_select_admin on public.share_history
  for select to authenticated
  using (public.is_admin_or_above());

-- ----------------------------------------------------- over_limit_records
create policy over_limit_records_select_admin on public.over_limit_records
  for select to authenticated
  using (public.is_admin_or_above());

-- --------------------------------------------------------- partner_shares
-- Partners see only their own share rows; admin/master_admin see all.

create policy partner_shares_select on public.partner_shares
  for select to authenticated
  using (
    partner_id = public.current_account_id()
    or public.is_admin_or_above()
  );

-- ------------------------------------------------------ warning_messages
create policy warning_messages_insert_admin on public.warning_messages
  for insert to authenticated
  with check (public.is_admin_or_above());

create policy warning_messages_select on public.warning_messages
  for select to authenticated
  using (
    public.is_admin_or_above()
    or (
      -- compare as text, not by casting current_role() into audience_role_type:
      -- current_role() can be 'admin'/'master_admin', which is not a valid
      -- audience_role_type value and would raise an error on cast instead of
      -- just evaluating false.
      audience_role::text = public.current_role()::text
      and (
        audience_scope = 'all'
        or exists (
          select 1 from public.session_targets st
          where st.warning_message_id = warning_messages.id
            and st.account_id = public.current_account_id()
        )
      )
    )
  );

-- -------------------------------------------------------- session_targets
create policy session_targets_insert_admin on public.session_targets
  for insert to authenticated
  with check (public.is_admin_or_above());

create policy session_targets_select on public.session_targets
  for select to authenticated
  using (
    account_id = public.current_account_id()
    or public.is_admin_or_above()
  );


-- ============================================================================
-- 7. NOTES FOR NEXT STEPS (not executed here)
-- ============================================================================
-- - Seed the Master Admin manually after this migration runs:
--     1. Create the auth.users row via Supabase Dashboard (Authentication ->
--        Add User) or the Admin API, using the master admin's real email.
--     2. Insert a matching row into public.accounts with role='master_admin',
--        auth_user_id = that user's id, email set, created_by = null.
-- - Edge Functions to build next: create-account, validate-bet-entry,
--   distribute-over-limit, calculate-pnl (all use the service role key and
--   therefore bypass RLS — they are the trusted layer that performs the
--   authoritative business-rule checks, e.g. the atomic limit check for
--   bet entries and the 100%-sum validation for partner share percentages).
-- - P&L (§4.3) is intentionally NOT a stored table here — compute it via a
--   SQL view/function (or inside calculate-pnl) from bet_entries,
--   partner_shares, and accounts.commission_rate/payout_rate at read time,
--   to avoid keeping a duplicate, driftable copy of derived numbers.
-- ============================================================================
